# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js 16 游릴
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies 游닌
        run: npm ci

      - name: Build 游댢
        run: npm run build:prod

      - name: 游 Archive austen-stone artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js 16 游릴
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies 游닌
        run: npm ci

      - name: Lint 九勇
        run: npm run lint

      - name: Test 游빍
        run: npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 拘勇 Download austen-stone artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: 404 GitHub Pages 丘멆잺
        run: cp austen-stone/index.html austen-stone/404.html

      - name: Deploy to GitHub Pages 游
        uses: crazy-max/ghaction-github-pages@v2
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          target_branch: gh-pages
          build_dir: austen-stone
          fqdn: austen.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
